[package]
name = "negation_normal_form"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bin_tree = {path = "../bin_tree"}
text_trees = "0.1.2"
