[package]
name = "truth_table"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boolean_evaluator = { path = "../boolean_evaluator"}
gray_code = {path = "../gray_code"}